---
apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-nginx-conf
data:
  default.conf: |
    upstream Backend {
      server hello;
    }
    server {
      listen       80;
      location / {
        proxy_pass http://Backend;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
        env: staging
    spec:
      containers:
        - name: nginx
          image: "gcr.io/google-samples/hello-frontend:1.0"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
              name: staging-nginx-conf
      volumes:
        - name: staging-nginx-conf
          configMap:
            name: staging-nginx-conf
            items:
              - key: default.conf
                path: default.conf
...
