---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: nginx
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
              name: production-nginx-conf
      volumes:
        - name: production-nginx-conf
          configMap:
            name: production-nginx-conf
            items:
              - key: default.conf
                path: default.conf
...
