---
apiVersion: v1
kind: Service
metadata:
  name: prodfrontend
spec:
  selector:
    app: hello
    tier: frontend
    env: production
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
...
