---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
      env: base
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
        env: base
    spec:
      containers:
        - name: hello
          image: "enxo/example-backend:base"
          ports:
            - name: http
              containerPort: 80
...
