---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
      env: base
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
        env: base
    spec:
      containers:
        - name: nginx
          image: "nginx:alpine"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
              name: base-nginx-conf
      volumes:
        - name: base-nginx-conf
          configMap:
            name: base-nginx-conf
            items:
              - key: default.conf
                path: default.conf
...
