apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
resources:
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
configMapGenerator:
- name: base-nginx-conf
  behavior: create
  files:
  - files/default.conf